<form method="POST" action="create_user.php">
    <label for="ufirstname">Entrer votre Prénom</label>
    <input type="text" name="firstname" id="ufirstname">
    <label for="ulastname">Entrer votre Nom</label>
    <input type="text" name="lastname" id="ulastname">
    <label for="email">Entrer votre E-mail</label>
    <input type="email" name="email" id="email">
    <label for="password">Entrer vote Mot De Passe</label>
    <input type="password" name="password" id="password">
    <input type="submit" value="Envoyer">
</form>

